server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:mem:customerdb
    username: sa
    password: password
    

# springdoc:
#   swagger-ui:
#     path: /swagger-ui.html
#     enabled: true
#   api-docs:
#     path: /v3/api-docs
#     enabled: true
#   packages-to-scan: com.yourcompany.customerservice
