server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          # uri: https://github.com/bachiriy/easybank  
          uri: /home/exshy/Documents/GitHub/Briefs/Microservices/EasyBank
          search-paths: configurations
          clone-on-start: true
